project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Graham Hurley" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Graham's Website"
  navbar:
    left:
      - href: index.qmd
        text: MyHome
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - Article.qmd
      - Academic Paper.qmd
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



