---
title: "Paper"
editor: visual
---

Humanity's Need for Efficient Coexistence with the Internet

Humanity has been entranced with the internet since its creation and as the internet evolves humanity's dependency on it grows. The internet has provided anyone with access to it an encyclopedia of the past and present of the world as well as multiple platforms where people can interact with each other. People can connect from anywhere on the planet as long as they have a device capable of connecting to Wifi. Thanks to global connectivity, the internet is now both the facilitator and the producer of human culture. The internet has allowed for the creation of online platforms where the exchange of ideas, memes, and culture can be easily accessed by anyone in the world. Online forums and social media platforms facilitate personalized culture in such a rapid manner to the point where humans are constantly itching for the next dose of dopamine and find themselves rapidly scrolling on their devices. As Johann Hari has shown in his article Your attention didn't collapse, the internet has stolen our attention, and the problem will only continue to worsen unless we find a way to combat it. Attention-seeking platforms are scattered throughout the internet that facilitates the exchange of ideas in both positive and toxic manners. Whitney Phillips' journal It Wasn't Just the Trolls: Early Internet Culture, "Fun," and the Fires of Exclusionary Laughter explains how early online forums and troll culture have created an internet of immense toxicity, racism, and negativity. An aspect of the internet that is incredibly dangerous is its speed of evolution. Artificial intelligence, social media, algorithms, and personalized content barely scratch the surface of the internet's capabilities in terms of keeping our attention. Even eye-tracking data is being studied and analyzed as a way to determine the most appealing placement of content on the screen as shown by Alexander Monea in Captured Time: Eye Tracking and the Attention Economy. 

It is a fact that the internet is evolving too fast to the point where humanity cannot live without it. The new generations of kids don\'t pick up the glove and ball, they watch YouTube Kids and play games on their iPads. The global distribution of technologies has in turn caused the fragmentation of media. Johann Hari's godson in his article, Your attention didn't collapse. It was stolen, is an example of how technologies that incorporate the internet are meticulously designed to grasp one's attention and anxieties. James J. Hodge's essay on anxiety Screwed: Anxiety and the Digital Ends of Anticipation explains how technologies adapt and take advantage of the anxieties of humans in simultaneously positive and negative manners. Internet algorithms and machine learning will evolve alongside children with internet access to cater content to their preferences. The question that researchers grapple with is how does humanity fight against these technological dependencies. The bottom line is that humanity has already become dependent on devices capable of accessing the internet. Due to the boundless amount of resources that the internet provides in information, communication, and pleasure, humanity will not reject its dependency. Rather than finding ways to shed our dependency on the internet, consumers need to look for ways to efficiently coexist with it.

Alexander Monea's work on eye-tracking exemplifies the dangers that technological evolution can have on our attention span. Base software, search engines, and social media platforms have designed algorithms to study and adapt to one's media habits. Monea believes that "human systems might be just as amenable to command, control, and communication as computational systems." The majority of laptops made today feature a camera as part of their specs. As Monea showed, Nvidia and companies pursuing VR(Virtual Reality) are beginning to use eye tracking as a feature of their systems to improve their products. In practice, it is conceptual and mainly unimproved as machine learning and algorithms study humans through their habits. The large fear of this technology is the inevitable selling of this data to platforms that employ machine learning. In addition to the ever-expanding knowledge that these platforms possess on their users from algorithms and machine learning, data from eye-tracking technologies will be used to further assess the habits of internet users. What kind of colors are people more drawn to, what fonts are more pleasurable to the eyes, and what designs will keep a user's attention for longer. The average human attention span is growing smaller and smaller thanks to the internet. According to Johann Hari, studies found that the average college student can only focus on one task for approximately 65 seconds and office workers cannot focus for longer than three minutes. Eye-tracking technology is a further manner to assess the attention span of humans visually. These statistics will continue to decrease with eye-tracking technology when it becomes practical as a way to further study technology and internet habits. Platforms will be able to personalize content locations to keep their consumers engaged with their products.
```
