---
title: "Article"
---
Are University Retention Rates in Washington D.C. Dropping? 

The freshman retention rate of the George Washington University\'s Class of 2022 fell close to one percentage point from the previous year, down to 92%.

\

Many of the colleges in the Washington Metropolitan Area share the quality of having costly tuition prices. Room and board can also be costly for students. Tuition for American University, Georgetown University and GW can all eclipse \$50,000 per year. The three institutions are situated in the district where neighbourhoods with sky-high real estate prices are commonplace. The extreme tuition prices that students have to pay for these schools could be a deterrent for students wanting to stay at these institutions.

\

Throughout the past 10 years the retention rate for The George Washington University (GW) has fluctuated between 90% and 93%. The current tuition at the university is \$56,845. Add room and board and the cost can be upwards of \$75,000. The number can differ depending on a student\'s room choice. To incentivize students into staying, the university has added more amenities in recent years including more dining dollars, \$30 in free printing and 34 loads of laundry. The past years have also seen changes to GW\'s curriculum that have drastically changed class offerings.

\

According to the National Center for Education Statistics, from 2016 to 2017, the national retention rate for students beginning in the fall semester seeking four year degrees was 81%. This number could be different for the Classes of 2021 and 2022. Sitting at roughly 87%, American University retention rate exceeds the national average freshman retention rate by 6%. Similar to GW, the retention rate at American fell by 1% from the 2017 class as the university\'s retention rate. Of the universities in the District that share similar tuition prices, American\'s retention rate is the lowest, though along with GW, it exceeds the national average.

\

Though its tuition rate is high, Georgetown University has a retention rate of 96% for its 2018 freshman class. Georgetown\'s rate is the highest among the colleges in the metro area. At 94%, Howard University\'s retention rate is the second highest among the private research universities in the area. But compared to the other private universities, Howard\'s tuition sits at \$26,756. Each one has different factors that contribute to their retention rates.

\

The University of Maryland College Park (UMD) retained about 95% of its 2018 freshmen, the same rate as the previous class. In state tuition for the university costs \$8,824 meanwhile out of state tuition is \$36,891. Compared with the universities within Washington, UMD\'s tuition prices are significantly lower. However, compared to other schools in the DC metro area, UMD is a state institution with a significantly larger student population that is primarily composed of in-state students.

\

In order to retain more of their freshman class, these institutions can look into methods that will encourage students to stay at their respective university.
